services:
  db:
    container_name: quotient_database
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - quotient_network
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s

  server:
    container_name: quotient_server
    image: quotient_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quotient_network
    volumes:
      - ./submissions:/app/submissions
      - ./config:/app/config
      - ./engine:/app/engine
      - ./static:/app/static
      - ./custom-checks:/app/checks

  divisor:
    build:
      context: divisor/
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    network_mode: host # Use host networking for divisor
    depends_on:
      db:
        condition: service_healthy
    privileged: true # Needed to manage networks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Needed to read runner names

networks:
  quotient_network:
    driver: bridge
